image: maven:3-jdk-8

cache:
 paths:
 - /root/.m2/repository

stages:
 - build
 - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && ssh-keyscan -H "$SSH_HOSTNAME_TESTING" > ~/.ssh/known_hosts'
  - scp root@$SSH_HOSTNAME_TESTING:~/bni-ecollection-1.0.0.jar /tmp/
  - mkdir -p .mvn/production-repository
  - mvn deploy:deploy-file -Durl=file://$(pwd)/.mvn/production-repository -DgroupId=id.co.bni.ecollection -DartifactId=bni-ecollection -Dversion=1.0.0 -Dpackaging=jar -Dfile=/tmp/bni-ecollection-1.0.0.jar

maven-build:
  image: maven:3-jdk-8
  stage: build
  services:
    - postgres:latest
  variables:
    POSTGRES_DB : "paymentbnidb"
    POSTGRES_USER: "paymentbni"
    POSTGRES_PASSWORD: "paymentbni123"
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/paymentbnidb
  script: mvn package -B -Pproduction -Dmaven.repo.local=.m2/repository
  artifacts:
    paths:
      - target/*.jar

deploy-to-testing:
  image: debian:latest
  stage: deploy
  only:
    - tags
  script:
  - scp target/*.jar root@$SSH_HOSTNAME_TESTING:/var/lib/bnisyariah-ecollection/
  - ssh root@$SSH_HOSTNAME_TESTING /var/lib/bnisyariah-ecollection/deploy.sh $CI_PROJECT_NAME-$CI_COMMIT_TAG.jar